# Generated by Django 5.2.11 on 2026-02-14 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_category_note_delete_notes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='categories',
            new_name='category',
        ),
    ]
